name: Reusable Greeting Workflow
on:
  workflow_call:
    inputs:
      person_name:
        description: "Name of the person"
        required: true
        type: string
      environment:
        type: string
        required: true

jobs:
  greet:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          # Now the input is passed from the caller
          echo "Hello, ${{ inputs.person_name }}!"
          # Environment secrets/variables are accessible here in the job's shell
          echo "Also, TEST_NAME from the environment is: $TEST_NAME"